// Example ray tracing program
// Written by Paolo Bonzini, 2005

#include <iostream>
#include "config.h"
#include "pngwrite.h"
#include "images.h"
#include "rand.h"

rng randf;

// Scrive l'immagine nel formato identificato da FMT, attualmente
// PNG o PPM binario.
bool Image::write (std::ostream &os, enum image_file_format fmt) const
{
  bool error = false;
  const char *data = reinterpret_cast <const char *> (get_image_data());

  if (fmt == OUT_PNG)
    error |= !write_png (os, data, width, height);
  else
    {
      os << "P6\n# Generated by " PACKAGE_STRING << std::endl
         << width << ' ' << height << std::endl
         << 255 << std::endl;

      os.write (data, 3 * width * height);
    }

  error |= !os;

  if (error)
    std::cerr << "File output error." << std::endl;

  return error;
}

